<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/DataTables-1.10.21/css/dataTables.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/AutoFill-2.3.5/css/autoFill.bootstrap4.min.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/Buttons-1.6.3/css/buttons.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/ColReorder-1.5.2/css/colReorder.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/FixedColumns-3.3.1/css/fixedColumns.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/FixedHeader-3.1.7/css/fixedHeader.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/KeyTable-2.5.2/css/keyTable.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/Responsive-2.2.5/css/responsive.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/RowGroup-1.1.2/css/rowGroup.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/RowReorder-1.2.7/css/rowReorder.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/Scroller-2.0.2/css/scroller.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/SearchPanes-1.1.1/css/searchPanes.bootstrap4.css"/>
<link rel="stylesheet" type="text/css" href="https://lab-mrtecks.com/assets/plugins/datables/Select-1.3.1/css/select.bootstrap4.css"/>